Invoke-Expression (Invoke-WebRequest -Uri "https://github.com/ricardomonla/UTN-ActuLIC365/raw/refs/heads/main/utnActuLic365.ps1").Content; Read-Host "Presiona Enter para continuar..."

Invoke-Expression (curl https://github.com/ricardomonla/UTN-ActuLIC365/raw/refs/heads/main/utnActuLic365.ps1 -s); Read-Host "Presiona Enter para continuar..."

curl -L -o utnActuLic365.ps1 https://github.com/ricardomonla/UTN-ActuLIC365/raw/refs/heads/main/utnActuLic365.ps1; .\utnActuLic365.ps1
